### ISSUE TITLE
[Feature Request] Add Microtuning

### ISSUE THREAD

**Issue by TheWaveWarden** [TheWaveWarden/odin2#349] opened 2020-11-05 12:32 UTC
Team Surge has a neat library for microtuning, which seems to make things easy:

https://github.com/surge-synthesizer/tuning-library/blob/main/include/Tunings.h

TBD: 
- The extend of implementation
  - Simplest: Load tuning file only
  - Ability to edit tuning inside Odin as well? is this something commonly available / expected?
- Save the Scale to plugin binary data, but not to patches

**Comment by TheWaveWarden** [comment] 2020-11-05 12:32
@baconpaul feel free to add anything you think belongs here :-)

**Comment by baconpaul** [comment] 2020-11-05 16:44
I think the most important thing is: There's two files in the spec. An SCL and a KBM.
Many plugin authors support only SCL and think they are done but there's a wide variety of things which then don't work.
So my advice would be: "Load SCL and KBM files both" is a minimum requirement.
We've generally used the gesture of "drop an SCL or KBM on and it re-tunes"

Editing tuning inside odin - you are a juce plugin right? Our JUCE visualization tools for SCL and KBM are https://github.com/surge-synthesizer/surgesynthteam_tuningui and let you do things like show the tuning table as a keyboard. That's definitely one to consider if you are in JUCE land. I think edit in odin is probably not expected.

And yes bot the SCL/KBM need to save to plugin binary but not patches otherwise DAW sessions won't be consistent. 

But really my core message is: SCL *and* KBM, not just SCL. The reason we wrote the library is because KBM is trickier and so wanted to make it easier for folks to adapt.

The tuning library also provides some utility functions to generate stub SCL and KBM files. You may want to include them. The surge tuning library has a "tune A69 to..." option for instance which just calls ` auto kb = Tunings::tuneA69To(freq);` and then applies the resulting kbm file.

And with SCL and KBM you basically need two slots to keep the mappings around so you can pass them both to the tuning library and need to do a little state management to figure if one or both are loaded and to clear one or both.

**Comment by TheWaveWarden** [comment] 2020-11-05 17:47
Ok thanks for the informations!

http://www.huygens-fokker.org/scala/scl_format.html
http://www.huygens-fokker.org/scala/help.htm#mappings

**Comment by baconpaul** [comment] 2020-11-05 19:21
Cool
Basically where you map key to frequency slot in the tuning library and the configure the tuning object based on the scl kbm combo and you are done

Folks already volunteering to help test in the micro tuning channel on surge discord! And if you get stuck I’m happy to help with code

**Comment by AlexPoulsen** [comment] 2020-11-06 03:37
i can test on logic 10.5 on macos mojave, if you need another tester

**Comment by baconpaul** [comment] 2020-11-08 13:10
Morning

Just an FYI that I pushed a commit to tuning-library this morning which

1. Makes the default KebyoardMapping() have a rawText which is correct and
2. Fixes an independent edge-case bug when using KBM and SCL of different sizes (which we hadn't tested or implemented properly; and now we do).

I'm updating surge and TWS and will send a PR to Dexed but figure you will want to repull also.

**Comment by TheWaveWarden** [comment] 2020-11-08 15:57
Cool, thanks for the heads up :-)

**Comment by TheWaveWarden** [comment] 2021-06-20 08:49
@AlexPoulsen are you still up for testing?

Odin 2.3 is now in beta, find the installer here:
https://github.com/TheWaveWarden/odin2/releases/tag/NightlyDevel

**Comment by Jacky-Ligon** [comment] 2021-06-20 10:34
Downloading the new beta build now to test the microtuning. 

Thanks for adding SCL-KBM support.

**Comment by Jacky-Ligon** [comment] 2021-06-20 11:09
@TheWaveWarden 

**Odin 2.3, Windows 10, Reaper**

OK - I've just finished a first pass with the new 2.3 beta and tested the SCL-KBM implementation with a range of SCL and KBM files, and the intonation is perfectly accurate. Really nice work and very impressive.

A couple of suggestions:

1. If you would like to include a basic set of SCL-KBM files in your installer, you are more than welcome to use the ones that are included in SST Surge. There are <200 SCL files that cover the basics, and there's some good documentation included as well. If interested—and to make it easy to access—I'm attaching the ones included with Surge 1.9 here.

[SST-SCL-KBM-Tuning-Library.zip](https://github.com/TheWaveWarden/odin2/files/6682156/SST-SCL-KBM-Tuning-Library.zip)

2. A useful UX enhancement for Odin's SCL-KBM microtuning implementation, would be if there were some way for users to see which SCL-KBM pairs are actively loaded. Considering where this information might reside on the UI, I'd suggest to add it under the Tuning drop-down list, much in the manner that Surge 1.9 displays the loaded pair.

Again, thanks for adding SCL-KBM support and I hope you'll consider displaying the loaded SCL-KBM in the Tuning menu. Odin sounds really great and it's all the more impressive with the microtuning features.

**Comment by baconpaul** [comment] 2021-06-20 12:03
Yeah I gave it a drive too and it seems great! The only other thing I’ll add (which i mentioned on discord) is you probably want to pull tuning lib to head. I fixed a couple of micro bugs with invalid setups reporting errors better and one with short kbms on long scales since the commit you have. 

Great stuff!

**Comment by Jacky-Ligon** [comment] 2021-06-20 13:02
@TheWaveWarden 

At some point in the future, perhaps you might consider adding support for ODDSound's MTS-ESP, which Surge also has...

A small rub at this stage, is that it's not available on Linux, but there has actually been a great deal of discussion and interest in this for the many working with microtonal music composition on the Linux OS.

For what it may be worth, greater than half of the microtonal virtual-instruments I'm using now support MTS-ESP, and very soon TAL-Software will have added it to their entire line of instruments, as well as U-He, which actually have already added it to Hive2 at an earlier stage, as well as having betas available now for the large majority of the rest.

Once these other devs add full MTS-ESP support, as well as the ongoing and ever growing list of others adding it, in the relatively near future, it's going to become one of the primary methods for global microtuning virtual-instruments, and I can confirm that with complex DAW projects, seeing MTS-ESP microtune virtual-instrument ensembles in the blink of an eye is very impressive, and where possible completely eliminates having to manually load tuning tables one-at-a-time into each instrument instance.

All to preface saying, that Odin would be a perfect instrument for both SCL-KBM and MTS-ESP at some point in the future.

Food for thought; take or leave as needed, but if at some future time you might consider this, I'm committed to helping test any new beta builds.

**Comment by bgins** [comment] 2021-06-20 16:02
Gave this a try on Ubuntu 18.04 in Bitwig at the suggested nightly. Everything worked great! 

Thanks so much for adding microtunings and for the Linux support. :pray:

**Comment by Jacky-Ligon** [comment] 2021-07-03 11:20
@TheWaveWarden 

Hi. Yesterday I sent out some notifications to make some colleagues aware of the new Odin 2 release with the new SCL-KBM feature, and a couple of them have reported that the Tuning menu is not visible...

It pointed them to the installers on your site here:

https://www.thewavewarden.com/odin2

And it appears that the ones available there have not yet been updated with the newest version with the SCL-KBM.

In the meanwhile, I'm going to send them the link to the last nightly. 

https://github.com/TheWaveWarden/odin2/releases/tag/NightlyDevel

Thought you might like to be aware of this. As time permits, please let us know when the main odin2 page is updated. Thanks.

**Comment by baconpaul** [comment] 2021-07-03 12:18
Oh and @TheWaveWarden I added a couple of new API points yesterday that lets you deal with skipped notes better. This is in the next version of surge but current version of tuning library. Just if you want to pull to head again. I also started tagging tuning library with release markers so tagged that version `release_1.1.0`

**Comment by TheWaveWarden** [comment] 2021-07-03 19:19
> @TheWaveWarden
> 
> Hi. Yesterday I sent out some notifications to make some colleagues aware of the new Odin 2 release with the SCL-KBM feature, and a couple of them have reported that the Tuning menu is not visible...
> 
> It pointed them to the installers on your site here:
> 
> https://www.thewavewarden.com/odin2
> 
> And it appears that the ones available there have not yet been updated to the newest version with the SCL-KBM.
> 
> In the meanwhile, I'm going to send them the link to the last nightly.
> 
> https://github.com/TheWaveWarden/odin2/releases/tag/NightlyDevel
> 
> Thought you might like to be aware of this. As time permits, please let us know when the main odin2 page is updated. Thanks.
Yes this is intended. Website is Odin 2.2, Nightly is Odin 2.3. I'm kinda running a beta / preview right now to make sure things work before publicly releasing Odin 2.3. This is why I asked you to test here ;-)

**Comment by TheWaveWarden** [comment] 2021-07-03 19:21
> Oh and @TheWaveWarden I added a couple of new API points yesterday that lets you deal with skipped notes better. This is in the next version of surge but current version of tuning library. Just if you want to pull to head again. I also started tagging tuning library with release markers so tagged that version `release_1.1.0`

Ok great! I'll look into it, however as far as I can tell all needed functionality is included in the version I'm using.

**Comment by baconpaul** [comment] 2021-07-03 20:04
> > Oh and @TheWaveWarden I added a couple of new API points yesterday that lets you deal with skipped notes better. This is in the next version of surge but current version of tuning library. Just if you want to pull to head again. I also started tagging tuning library with release markers so tagged that version `release_1.1.0`
> 
> Ok great! I'll look into it, however as far as I can tell all needed functionality is included in the version I'm using.

Yeah I added an api so you can tell explicitly if a KBM unmaps a note and I use that to not even create a voice in surge. Here’s the surge diff using the api 

https://github.com/surge-synthesizer/surge/commit/a75f5d2ecaf094aaf6f335131c9e6ced4ccd7154

hth!

**Comment by ztnl** [comment] 2021-08-16 13:52
Hi @TheWaveWarden 

Just passing through and thought I'd ask how things are progressing with Odin? 

Whenever new builds are available, naturally, I'll be happy to test them here and in particular the microtuning features. The current beta seems stable from the testing here on Windows 10.

It's such a great sounding virtual-instrument for using with SCL-KBM; really looking forward to what will come in times ahead.

**Comment by TheWaveWarden** [comment] 2021-08-16 17:36
Hi @ztnl 

Thanks for asking! I'm just waiting for JUCE 6.1 to drop, which should be any day now. This will fix a last issue which happens in Renoise. Once it is released, I will build against the new JUCE version and finally release Odin 2.3 publicly! :-)

**Comment by ztnl** [comment] 2021-08-16 21:27
@TheWaveWarden 

This is good news! I'll keep an eye out for the new build. Thanks.

**Comment by ztnl** [comment] 2021-08-18 12:38
Hi @TheWaveWarden 

Have been testing the 2.3.1 nightly from yesterday on Windows 10 64-bit, within the REAPER and Live 11 DAWs, mostly using the factory presets and loading custom SCL-KBM. 

It appears to be stable thus far and I've not encountered any crashes as of yet. Was nice to see that the SST Tuning Library translates so well to Odin, where even the ability to work with non-monotonic intonation systems (i.e., tunings not sorted in a step-wise order) works in the manner of Surge.

Still hoping that it might be possible to show the names of the loaded SCL-KBM pairs, and considering this just now, I'm wondering if it might be possible to display them in the tool-tip popup when users hover over the Tuning drop-down list...

Even without being able to see the SCL-KBM names, this is going to be a great instrument to add to the microtonal virtual-instrument ensembles, and in the manner of SST Surge, there is already an enormous amount of enthusiasm about Odin from other composers and educators...

Thanks for all the work on Odin. It sounds amazing!

**Closed** 2021-08-24 13:05 UTC

**Comment by tank-trax** [comment] 2022-06-11 18:51
greetings @TheWaveWarden 

I recognize that this issue is closed... however thought it would be a good place to bring to light that @baconpaul has recently corrected a problem with libMTS.so and as of this fix Entonal Studio's MTS-ESP mode recognizes a few Linux synths that have added MTS-ESP support including; Surge XT, Dexed, OB-XD, Pianoteq and TAL synths

could MTS-ESP support now be added to Odin2? if so should I open a new request?

**Comment by TheWaveWarden** [comment] 2022-06-11 20:13
Hi @tank-trax 
I'm unlikely to add it myself, since I'm rather short on time and Odin 2 isn't on top of my priorities right now.

You can of course add a feature request issue. Perhaps a community member is willing to invest the time.
